import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <script dangerouslySetInnerHTML={{ __html: `
          window.onpopstate = function() {
            window.location.reload();
          };
          window.addEventListener('pageshow', function(e) {
            if (e.persisted) window.location.reload();
          });
          window.writeCookie = function(days) {
            var date = new Date();
            days = days || 1;
            date.setTime(+date + (days * 86400000));
            document.cookie = 'RS_Promotion=1; expires=' + date.toGMTString() + '; path=/';
            var el = document.getElementById('Promotion');
            if (el) el.style.display = 'none';
          };
          window.getCookie = function(name) {
            var v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
            return v ? v[2] : null;
          };
        ` }} />
      </body>
    </html>
  );
}
